export const SET_MENU_ITEM_INDEX = 'SET_MENU_ITEM_INDEX';
export const SET_FEAT_ITEM_INDEX = 'SET_FEAT_ITEM_INDEX';
export const SET_EDIT_DATA_FLAG = 'SET_EDIT_DATA_FLAG';
export const SET_ADD_DATA_FLAG = 'SET_ADD_DATA_FLAG';
export const EDIT_DATA_FAILURE = 'EDIT_DATA_FAILURE';
export const CLEAR_EDIT_DATA_FAILURE = 'CLEAR_EDIT_DATA_FAILURE';
export const SET_SHOW_ADD_METRIC = 'SET_SHOW_ADD_METRIC';