export const FETCH_SUMMARY_DATA_BEGIN = 'FETCH_SUMMARY_DATA_BEGIN';
export const FETCH_SUMMARY_DATA_SUCCESS = 'FETCH_SUMMARY_DATA_SUCCESS';
export const FETCH_SUMMARY_DATA_FAILURE = 'FETCH_SUMMARY_DATA_FAILURE';

export const SHOW_PROFILE_MENU = 'SHOW_PROFILE_MENU';
export const SHOW_CSV_DOWNLOAD_MENU = 'SHOW_CSV_DOWNLOAD_MENU';
export const SHOW_CSV_UPLOAD_MENU = 'SHOW_CSV_UPLOAD_MENU';
export const SUBMIT_CSV_LOAD_SUCCESS = 'SUBMIT_CSV_LOAD_SUCCESS';
export const SUBMIT_CSV_LOAD_FAILURE = 'SUBMIT_CSV_LOAD_FAILURE';
export const CSV_LOAD_CONFIRM = 'CSV_LOAD_CONFIRM';
export const CSV_LOAD_CLEAR = 'CSV_LOAD_CLEAR';
export const CLEAR_CSV_LOAD_CONFIRM = 'CLEAR_CSV_LOAD_CONFIRM';
export const DATA_POINTS_REFRESH = 'DATA_POINTS_REFRESH';
export const ADD_BLANK_PARAM = 'ADD_BLANK_PARAM';

export const SHOW_INTERVENTIONS_MENU = 'SHOW_INTERVENTIONS_MENU';
export const PROFILE_MENU_FETCH_SUCCESS = 'PROFILE_MENU_FETCH_SUCCESS';
export const PROFILE_MENU_FETCH_FAILURE = 'PROFILE_MENU_FETCH_FAILURE';
export const PROFILE_MENU_EDIT_SUCCESS = 'PROFILE_MENU_EDIT_SUCCESS';
export const PROFILE_MENU_EDIT_FAILURE = 'PROFILE_MENU_EDIT_FAILURE';
export const CLEAR_PROFILE_UPDATE_STATUS = 'CLEAR_PROFILE_UPDATE_STATUS';
export const SUMMARY_ITEMS_REFRESH = 'SUMMARY_ITEMS_REFRESH';



