export const FETCH_SUMMARY_DATA_BEGIN = 'FETCH_SUMMARY_DATA_BEGIN';
export const FETCH_SUMMARY_DATA_SUCCESS = 'FETCH_SUMMARY_DATA_SUCCESS';
export const FETCH_SUMMARY_DATA_FAILURE = 'FETCH_SUMMARY_DATA_FAILURE';

export const SHOW_PROFILE_MENU = 'SHOW_PROFILE_MENU';
export const SHOW_CSV_DOWNLOAD_MENU = 'SHOW_CSV_DOWNLOAD_MENU';
export const SHOW_CSV_UPLOAD_MENU = 'SHOW_CSV_UPLOAD_MENU';
export const SUBMIT_CSV_LOAD_SUCCESS = 'SUBMIT_CSV_LOAD_SUCCESS';
export const SUBMIT_CSV_LOAD_FAILURE = 'SUBMIT_CSV_LOAD_FAILURE';
export const CSV_LOAD_CONFIRM = 'CSV_LOAD_CONFIRM';
export const CSV_LOAD_CLEAR = 'CSV_LOAD_CLEAR';
export const CLEAR_CSV_LOAD_CONFIRM = 'CLEAR_CSV_LOAD_CONFIRM';
export const DATA_POINTS_REFRESH = 'DATA_POINTS_REFRESH';

export const SHOW_INTERVENTIONS_MENU = 'SHOW_INTERVENTIONS_MENU';
export const PROFILE_MENU_FETCH_SUCCESS = 'PROFILE_MENU_FETCH_SUCCESS';
export const PROFILE_MENU_FETCH_FAILURE = 'PROFILE_MENU_FETCH_FAILURE';
export const PROFILE_MENU_EDIT_SUCCESS = 'PROFILE_MENU_EDIT_SUCCESS';
export const PROFILE_MENU_EDIT_FAILURE = 'PROFILE_MENU_EDIT_FAILURE';
export const SHOW_MENU_EDIT_SUCCESS = 'SHOW_MENU_EDIT_SUCCESS';
export const CLEAR_PROFILE_UPDATE_STATUS = 'CLEAR_PROFILE_UPDATE_STATUS';
export const TARGETS_DATA_REFRESH = 'TARGETS_DATA_REFRESH';
export const UNIT_INFO_REFRESH = 'UNIT_INFO_REFRESH';
export const POST_CUSTOM_PARAM_FAILURE = 'POST_CUSTOM_PARAM_FAILURE';
export const UPDATE_BOOKMARKS = 'UPDATE_BOOKMARKS';
export const UPDATE_LINKED_PARAMS = 'UPDATE_LINKED_PARAMS';
